apiVersion: v2
name: aws-event-sources
version: 0.1.0
appVersion: 0.2.0
type: application
description: A Helm chart for AWS event sources by Triggermesh
home: https://github.com/triggermesh/aws-event-sources
icon: file://../logo.png
keywords:
  - knative-eventing
  - sources
  - aws
  - triggermesh
  - serverless
maintainers:
  - name: sameersbn
  - name: antoineco
sources:
  - https://github.com/triggermesh/aws-event-sources
