apiVersion: v1
name: aws-event-sources
version: 0.1.2
appVersion: 0.3.0
description: AWS Event Sources controller for Kubernetes
home: https://github.com/triggermesh/aws-event-sources
icon: file://../logo.svg
keywords:
  - knative-eventing
  - sources
  - aws
  - triggermesh
  - serverless
maintainers:
  - name: sameersbn
  - name: antoineco
sources:
  - https://github.com/triggermesh/aws-event-sources
